# Generated by Django 5.1.7 on 2025-03-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLStandardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('template', models.TextField(verbose_name='XML-Vorlage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Branche')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'XML-Standardvorlage',
                'verbose_name_plural': 'XML-Standardvorlagen',
                'ordering': ['name', 'version'],
            },
        ),
    ]
