# Generated by Django 5.1.7 on 2025-04-11 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('interfaces', '0001_initial'),
        ('order', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacelog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_logs',
                                    to='order.purchaseorder', verbose_name='Bestellung'),
        ),
        migrations.AddField(
            model_name='supplierinterface',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='created_interfaces', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='supplierinterface',
            name='interface_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interfaces.interfacetype',
                                    verbose_name='Schnittstellentyp'),
        ),
        migrations.AddField(
            model_name='supplierinterface',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces',
                                    to='suppliers.supplier', verbose_name='Lieferant'),
        ),
        migrations.AddField(
            model_name='interfacelog',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs',
                                    to='interfaces.supplierinterface', verbose_name='Schnittstelle'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierinterface',
            unique_together={('supplier', 'name')},
        ),
    ]
