# Generated by Django 5.1.7 on 2025-03-16 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_currency'),
        ('suppliers', '0003_supplier_minimum_order_value_supplier_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='core.currency', verbose_name='Währung'),
        ),
    ]
