# Generated by Django 5.1.7 on 2025-03-16 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_currency'),
        ('suppliers', '0004_supplierproduct_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='core.currency', verbose_name='Standardwährung'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='core.currency', verbose_name='Währung'),
        ),
    ]
