# Generated by Django 5.1.7 on 2025-03-08 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouses',
            field=models.ManyToManyField(through='core.ProductWarehouse', to='inventory.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='productwarehouse',
            unique_together={('product', 'warehouse')},
        ),
    ]
