# Generated by Django 5.1.7 on 2025-03-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='error_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importlog',
            name='import_type',
            field=models.CharField(choices=[('products', 'Products'), ('categories', 'Categories'), ('suppliers', 'Suppliers'), ('supplier_products', 'Supplier Products'), ('warehouses', 'Warehouses'), ('departments', 'Departments'), ('warehouse_products', 'Warehouse Products')], default='products', max_length=50),
        ),
        migrations.AddField(
            model_name='importlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importlog',
            name='rows_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importlog',
            name='rows_error',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importlog',
            name='rows_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importlog',
            name='rows_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('processing', 'Processing'), ('failed', 'Failed')], default='processing', max_length=25),
        ),
    ]
