# Generated by Django 5.1.7 on 2025-03-09 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_importlog_error_details_importlog_import_type_and_more'),
        ('inventory', '0002_department_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_view_inventory', 'Kann Lagerverwaltung ansehen'), ('can_edit_inventory', 'Kann Lagerverwaltung bearbeiten'), ('can_create_inventory', 'Kann in Lagerverwaltung erstellen'), ('can_delete_inventory', 'Kann in Lagerverwaltung löschen'), ('can_admin_inventory', 'Kann Lagerverwaltung administrieren')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.ManyToManyField(blank=True, related_name='user_profiles', to='inventory.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
