# Generated by Django 5.1 on 2025-03-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_current_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='current_stock',
        ),
    ]
