# Generated by Django 5.1.7 on 2025-03-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_batchnumber_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermission',
            options={'default_permissions': (), 'managed': False, 'permissions': (('can_view_inventory', 'Kann Lagerverwaltung ansehen'), ('can_edit_inventory', 'Kann Lagerverwaltung bearbeiten'), ('can_create_inventory', 'Kann in Lagerverwaltung erstellen'), ('can_delete_inventory', 'Kann in Lagerverwaltung löschen'), ('can_admin_inventory', 'Kann Lagerverwaltung administrieren'), ('can_view_order', 'Kann Bestellungen ansehen'), ('can_edit_order', 'Kann Bestellungen bearbeiten'), ('can_create_order', 'Kann Bestellungen erstellen'), ('can_delete_order', 'Kann Bestellungen löschen'), ('can_approve_order', 'Kann Bestellungen genehmigen'))},
        ),
    ]
