# Generated by Django 5.1 on 2025-03-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_custompermission_options'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='organization.department'),
        ),
    ]
