# Generated by Django 5.1.7 on 2025-03-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tax_delete_custompermission_product_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., EUR, USD)', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=5)),
                ('decimal_places', models.IntegerField(default=2)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate relative to the default currency', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Währung',
                'verbose_name_plural': 'Währungen',
                'ordering': ['code'],
            },
        ),
    ]
