# Generated by Django 5.1.7 on 2025-04-17 19:56

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the module', max_length=100)),
                ('code',
                 models.CharField(help_text='Unique code identifier for the module', max_length=50, unique=True)),
                ('description',
                 models.TextField(blank=True, help_text="Detailed description of the module's functionality")),
                ('is_active',
                 models.BooleanField(default=True, help_text='Whether this module is currently available')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                                      help_text='Monthly subscription price for this module',
                                                      max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                                     help_text='Yearly subscription price for this module',
                                                     max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the feature flag', max_length=100)),
                ('code',
                 models.CharField(help_text='Unique code identifier for the feature flag', max_length=50, unique=True)),
                ('description',
                 models.TextField(blank=True, help_text='Detailed description of what this feature flag controls')),
                ('is_active',
                 models.BooleanField(default=True, help_text='Whether this feature flag is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags',
                                             to='module_management.module')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subscription package', max_length=100)),
                ('code',
                 models.CharField(help_text='Unique code identifier for the package', max_length=50, unique=True)),
                ('description',
                 models.TextField(blank=True, help_text="Detailed description of what's included in this package")),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                                      help_text='Monthly subscription price for this package',
                                                      max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                                     help_text='Yearly subscription price for this package',
                                                     max_digits=10)),
                ('is_active',
                 models.BooleanField(default=True, help_text='Whether this package is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_flags', models.ManyToManyField(blank=True, related_name='subscription_packages',
                                                         to='module_management.featureflag')),
                ('modules',
                 models.ManyToManyField(related_name='subscription_packages', to='module_management.module')),
            ],
            options={
                'verbose_name': 'Subscription Package',
                'verbose_name_plural': 'Subscription Packages',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type',
                 models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('trial', 'Trial')],
                                  default='monthly', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('payment_status', models.CharField(
                    choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'),
                             ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('custom_settings',
                 models.TextField(blank=True, help_text='JSON string with custom subscription settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_features',
                 models.ManyToManyField(blank=True, help_text='Additional features not included in the package',
                                        related_name='custom_subscriptions', to='module_management.featureflag')),
                ('custom_modules',
                 models.ManyToManyField(blank=True, help_text='Additional modules not included in the package',
                                        related_name='custom_subscriptions', to='module_management.module')),
                ('organization',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions',
                                   to='master_data.organization')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions',
                                              to='module_management.subscriptionpackage')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-start_date'],
            },
        ),
    ]
