# Generated by Django 5.1.7 on 2025-04-11 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_manage_stock', models.BooleanField(default=False)),
                ('department',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Warehouse Access Rights',
                'unique_together': {('warehouse', 'department')},
            },
        ),
    ]
