# Generated by Django 5.1.7 on 2025-04-04 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('access_admin', 'Can access admin dashboard'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_view_inventory', 'Kann Lagerverwaltung ansehen'), ('can_edit_inventory', 'Kann Lagerverwaltung bearbeiten'), ('can_create_inventory', 'Kann in Lagerverwaltung erstellen'), ('can_delete_inventory', 'Kann in Lagerverwaltung löschen'), ('can_admin_inventory', 'Kann Lagerverwaltung administrieren'), ('can_view_product', 'Kann Produktverwaltung ansehen'), ('can_edit_product', 'Kann Produktverwaltung bearbeiten'), ('can_create_product', 'Kann in Produktverwaltung erstellen'), ('can_delete_product', 'Kann in Produktverwaltung löschen'), ('can_admin_product', 'Kann Produktverwaltung administrieren'), ('can_view_supplier', 'Kann Lieferantenverwaltung ansehen'), ('can_edit_supplier', 'Kann Lieferantenverwaltung bearbeiten'), ('can_create_supplier', 'Kann in Lieferantenverwaltung erstellen'), ('can_delete_supplier', 'Kann in Lieferantenverwaltung löschen'), ('can_admin_supplier', 'Kann Lieferantenverwaltung administrieren'), ('can_view_report', 'Kann Berichtswesen ansehen'), ('can_edit_report', 'Kann Berichtswesen bearbeiten'), ('can_create_report', 'Kann in Berichtswesen erstellen'), ('can_delete_report', 'Kann in Berichtswesen löschen'), ('can_admin_report', 'Kann Berichtswesen administrieren'), ('can_view_import', 'Kann Datenimport ansehen'), ('can_edit_import', 'Kann Datenimport bearbeiten'), ('can_create_import', 'Kann in Datenimport erstellen'), ('can_delete_import', 'Kann in Datenimport löschen'), ('can_admin_import', 'Kann Datenimport administrieren'), ('can_view_order', 'Kann Bestellungen ansehen'), ('can_edit_order', 'Kann Bestellungen bearbeiten'), ('can_create_order', 'Kann Bestellungen erstellen'), ('can_delete_order', 'Kann Bestellungen löschen'), ('can_approve_order', 'Kann Bestellungen genehmigen'), ('can_admin_order', 'Kann Bestellverwaltung administrieren'), ('access_admin', 'Can access admin dashboard')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WarehouseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_manage_stock', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
            ],
            options={
                'verbose_name_plural': 'Warehouse Access Rights',
            },
        ),
    ]
