# Generated by Django 5.1 on 2025-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('access_admin', 'Can access admin dashboard'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
