# Generated by Django 5.1.7 on 2025-04-04 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessmanagement', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseaccess',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouseaccess',
            unique_together={('warehouse', 'department')},
        ),
    ]
