# Generated by Django 5.1.7 on 2025-04-04 08:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0001_initial'),
        ('order', '0002_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(max_length=50, unique=True, verbose_name='RMA-Nummer')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('pending', 'In Bearbeitung'), ('approved', 'Genehmigt'), ('sent', 'An Lieferant gesendet'), ('resolved', 'Erledigt'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], default='draft', max_length=20, verbose_name='Status')),
                ('resolution_type', models.CharField(blank=True, choices=[('replacement', 'Ersatz'), ('refund', 'Rückerstattung'), ('credit', 'Gutschrift'), ('repair', 'Reparatur'), ('no_action', 'Keine Maßnahme')], max_length=20, null=True, verbose_name='Art der Lösung')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Lösungsdetails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('submission_date', models.DateTimeField(blank=True, null=True, verbose_name='Eingereicht am')),
                ('resolution_date', models.DateTimeField(blank=True, null=True, verbose_name='Gelöst am')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Kontaktperson')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Kontakt E-Mail')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Kontakt Telefon')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Rücksendeadresse')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Tracking-Nummer')),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='Versanddatum')),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Gesamtwert')),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkungen')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rmas', to=settings.AUTH_USER_MODEL, verbose_name='Genehmigt von')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rmas', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmas', to='order.purchaseorder', verbose_name='Zugehörige Bestellung')),
                ('rma_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_items', to='inventory.warehouse', verbose_name='RMA-Lager')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'RMA',
                'verbose_name_plural': 'RMAs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RMAComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='rma_attachments/', verbose_name='Anhang')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='Anhangsname')),
                ('is_public', models.BooleanField(default=False, help_text='Wenn aktiviert, ist dieser Kommentar auch für den Lieferanten sichtbar', verbose_name='Öffentlich sichtbar')),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rma.rma', verbose_name='RMA')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'RMA-Kommentar',
                'verbose_name_plural': 'RMA-Kommentare',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RMADocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('shipping_label', 'Versandetikett'), ('return_auth', 'Rücksendeerlaubnis'), ('supplier_response', 'Lieferantenantwort'), ('credit_note', 'Gutschrift'), ('other', 'Sonstiges')], max_length=50, verbose_name='Dokumenttyp')),
                ('file', models.FileField(upload_to='rma_documents/', verbose_name='Datei')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkungen')),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rma.rma', verbose_name='RMA')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'RMA-Dokument',
                'verbose_name_plural': 'RMA-Dokumente',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RMAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zeitstempel')),
                ('status_from', models.CharField(blank=True, choices=[('draft', 'Entwurf'), ('pending', 'In Bearbeitung'), ('approved', 'Genehmigt'), ('sent', 'An Lieferant gesendet'), ('resolved', 'Erledigt'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], max_length=20, null=True, verbose_name='Status vorher')),
                ('status_to', models.CharField(blank=True, choices=[('draft', 'Entwurf'), ('pending', 'In Bearbeitung'), ('approved', 'Genehmigt'), ('sent', 'An Lieferant gesendet'), ('resolved', 'Erledigt'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], max_length=20, null=True, verbose_name='Status nachher')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Geändert von')),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rma.rma', verbose_name='RMA')),
            ],
            options={
                'verbose_name': 'RMA-Verlauf',
                'verbose_name_plural': 'RMA-Verlauf',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RMAItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Menge')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stückpreis')),
                ('issue_type', models.CharField(choices=[('defective', 'Defekt'), ('damaged', 'Beschädigt'), ('wrong_item', 'Falscher Artikel'), ('wrong_quantity', 'Falsche Menge'), ('expired', 'Abgelaufen'), ('other', 'Sonstiges')], max_length=20, verbose_name='Problemtyp')),
                ('issue_description', models.TextField(verbose_name='Problembeschreibung')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Chargennummer')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seriennummer')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Verfallsdatum')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Lösungsdetails')),
                ('has_photos', models.BooleanField(default=False, verbose_name='Hat Fotos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Produkt')),
                ('receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_items', to='order.purchaseorderreceiptitem', verbose_name='Ursprünglicher Wareneingang')),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rma.rma', verbose_name='RMA')),
            ],
            options={
                'verbose_name': 'RMA-Position',
                'verbose_name_plural': 'RMA-Positionen',
            },
        ),
        migrations.CreateModel(
            name='RMAPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rma_photos/', verbose_name='Bild')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Bildunterschrift')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('rma_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rma.rmaitem', verbose_name='RMA-Position')),
            ],
            options={
                'verbose_name': 'RMA-Foto',
                'verbose_name_plural': 'RMA-Fotos',
            },
        ),
    ]
