# Generated by Django 5.1.7 on 2025-03-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminDashboardPermission',
        ),
    ]
