# Generated by Django 5.1.7 on 2025-03-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_department_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='count_frequency',
            field=models.IntegerField(default=0, help_text='0 = einmalige Inventur, >0 = Zyklus in Tagen für rollierende Inventur', verbose_name='Zählfrequenz in Tagen'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='cycle_count_category',
            field=models.CharField(blank=True, choices=[('A', 'A-Artikel (hoher Wert/Umschlag)'), ('B', 'B-Artikel (mittlerer Wert/Umschlag)'), ('C', 'C-Artikel (niedriger Wert/Umschlag)'), ('', 'Alle Artikel')], max_length=1, verbose_name='Artikelkategorie für rollierende Inventur'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='display_expected_quantity',
            field=models.BooleanField(default=True, help_text='Wenn deaktiviert, werden den Zählern die erwarteten Mengen nicht angezeigt (Blindzählung)', verbose_name='Erwartete Mengen anzeigen'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='inventory_type',
            field=models.CharField(choices=[('full', 'Komplettinventur'), ('rolling', 'Rollierende Inventur'), ('blind', 'Blindzählung'), ('sample', 'Stichprobeninventur')], default='full', max_length=20, verbose_name='Inventurtyp'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='last_cycle_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum der letzten Zykleninventur'),
        ),
    ]
