# Generated by Django 5.1 on 2025-03-13 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_userprofile_departments'),
        ('inventory', '0003_stocktake_count_frequency_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseaccess',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
