# Generated by Django 5.1 on 2025-03-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_warehouseaccess_department_delete_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WarehouseAccess',
        ),
    ]
