# Generated by Django 5.1.7 on 2025-04-11 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('order', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='matched_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='delivery_documents', to='order.purchaseorder'),
        ),
        migrations.AddField(
            model_name='document',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='documents', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentmatch',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_attempts',
                                    to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentmatch',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='document_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentmatch',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='document_matches', to='order.purchaseorder'),
        ),
        migrations.AddField(
            model_name='documentprocessinglog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs',
                                    to='documents.document'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='reference_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='derived_templates', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates',
                                    to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='documentmatch',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_matches',
                                    to='documents.documenttemplate'),
        ),
        migrations.AddField(
            model_name='document',
            name='matched_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='matched_documents', to='documents.documenttemplate'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates',
                                    to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents',
                                    to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='standardfield',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_fields',
                                    to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='reference_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='dependent_fields', to='documents.templatefield'),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='table_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='table_fields', to='documents.templatefield'),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields',
                                    to='documents.documenttemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together={('name', 'supplier', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='standardfield',
            unique_together={('code', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='templatefield',
            unique_together={('template', 'code')},
        ),
    ]
