# Generated by Django 5.1.7 on 2025-03-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('currency', 'Currency'), ('boolean', 'Boolean'), ('list', 'List of Items'), ('table', 'Table')], default='text', max_length=20)),
                ('extraction_method', models.CharField(choices=[('exact', 'Exact Position'), ('label_based', 'Based on Label'), ('relative', 'Relative to Another Field'), ('regex', 'Regular Expression'), ('table_cell', 'Table Cell')], default='label_based', max_length=20)),
                ('search_pattern', models.CharField(blank=True, help_text='Label or regex pattern to find the field', max_length=255)),
                ('is_key_field', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order for display')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_fields', to='documents.documenttype')),
            ],
            options={
                'verbose_name': 'Standard Field',
                'verbose_name_plural': 'Standard Fields',
                'ordering': ['document_type', 'order', 'name'],
            },
        ),
    ]
