# Generated by Django 5.1.7 on 2025-03-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_standardfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardfield',
            name='original_code',
            field=models.CharField(blank=True, help_text='Original field code used for extraction', max_length=50),
        ),
        migrations.AlterField(
            model_name='standardfield',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='standardfield',
            unique_together={('code', 'document_type')},
        ),
    ]
