# Generated by Django 5.1.7 on 2025-04-04 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_order_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vorlagenname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Wiederkehrend')),
                ('recurrence_frequency', models.CharField(choices=[('none', 'Keine Wiederholung'), ('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('biweekly', 'Alle zwei Wochen'), ('monthly', 'Monatlich'), ('quarterly', 'Vierteljährlich'), ('semiannual', 'Halbjährlich'), ('annual', 'Jährlich')], default='none', max_length=20, verbose_name='Häufigkeit')),
                ('next_order_date', models.DateField(blank=True, null=True, verbose_name='Nächstes Bestelldatum')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Lieferadresse')),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkungen')),
            ],
            options={
                'verbose_name': 'Bestellvorlage',
                'verbose_name_plural': 'Bestellvorlagen',
                'ordering': ['supplier__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Menge')),
                ('supplier_sku', models.CharField(blank=True, max_length=100, verbose_name='Lieferanten-Artikelnummer')),
            ],
            options={
                'verbose_name': 'Vorlagenposition',
                'verbose_name_plural': 'Vorlagenpositionen',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('pending', 'Wartend auf Genehmigung'), ('approved', 'Genehmigt'), ('sent', 'Bestellt'), ('partially_received', 'Teilweise erhalten'), ('received', 'Vollständig erhalten'), ('cancelled', 'Storniert')], default='draft', max_length=20)),
                ('shipping_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('note', 'Note'), ('status_change', 'Status Change'), ('system', 'System Notification')], default='note', max_length=20)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, help_text='If true, the comment will be visible to suppliers in the supplier portal')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='order_comments/')),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Bestellkommentar',
                'verbose_name_plural': 'Bestellkommentare',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('partially_canceled', 'Partially Canceled')], default='active', max_length=20)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('canceled_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_sku', models.CharField(blank=True, max_length=100)),
                ('item_notes', models.TextField(blank=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Der zum Zeitpunkt der Bestellung gültige Mehrwertsteuersatz', max_digits=5, verbose_name='MwSt-Satz')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bezeichnung für diese Teillieferung', max_length=100, verbose_name='Bezeichnung')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Erwarteter Liefertermin')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('in_transit', 'In Transit'), ('received', 'Erhalten'), ('cancelled', 'Storniert')], default='planned', max_length=20, verbose_name='Status')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Tracking-Nummer')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Spediteur/Lieferant')),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_splits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teillieferung',
                'verbose_name_plural': 'Teillieferungen',
                'ordering': ['purchase_order', 'expected_delivery'],
            },
        ),
        migrations.CreateModel(
            name='OrderSplitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Menge')),
                ('order_split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.ordersplit')),
            ],
            options={
                'verbose_name': 'Teillieferungsposition',
                'verbose_name_plural': 'Teillieferungspositionen',
            },
        ),
    ]
