# Generated by Django 5.1.7 on 2025-03-13 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tax_delete_custompermission_product_tax'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax',
            field=models.ForeignKey(help_text='Der zum Zeitpunkt der Bestellung gültige Mehrwertsteuersatz', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tax', verbose_name='Mehrwertsteuersatz'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Der zum Zeitpunkt der Bestellung gültige Mehrwertsteuersatz', max_digits=5, verbose_name='MwSt-Satz'),
        ),
    ]
