# Generated by Django 5.1.7 on 2025-04-11 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('admin_dashboard', '0002_initial'),
        ('core', '0002_initial'),
        ('inventory', '0001_initial'),
        ('order', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersuggestion',
            name='preferred_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='ordersuggestion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='ordertemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_templates',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordertemplate',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier',
                                    verbose_name='Lieferant'),
        ),
        migrations.AddField(
            model_name='ordertemplateitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='ordertemplateitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                    to='order.ordertemplate'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='purchase_orders_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='billing_orders', to='admin_dashboard.companyaddress',
                                    verbose_name='Rechnungsadresse'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_created',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='shipping_orders', to='admin_dashboard.companyaddress',
                                    verbose_name='Versandadresse'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='template_source',
            field=models.ForeignKey(blank=True, help_text='Die Vorlage, aus der diese Bestellung erstellt wurde',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='generated_orders', to='order.ordertemplate',
                                    verbose_name='Erstellungsvorlage'),
        ),
        migrations.AddField(
            model_name='ordersplit',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits',
                                    to='order.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseordercomment',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                    to='order.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseordercomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='order_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='canceled_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='currency',
            field=models.ForeignKey(help_text='Die Währung, in der der Artikel bestellt wird', null=True,
                                    on_delete=django.db.models.deletion.PROTECT, to='core.currency',
                                    verbose_name='Währung'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                    to='order.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax',
            field=models.ForeignKey(help_text='Der zum Zeitpunkt der Bestellung gültige Mehrwertsteuersatz', null=True,
                                    on_delete=django.db.models.deletion.PROTECT, to='core.tax',
                                    verbose_name='Mehrwertsteuersatz'),
        ),
        migrations.AddField(
            model_name='ordersplititem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_items',
                                    to='order.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='purchaseorderreceipt',
            name='order_split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='receipts', to='order.ordersplit', verbose_name='Teillieferung'),
        ),
        migrations.AddField(
            model_name='purchaseorderreceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts',
                                    to='order.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderreceipt',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderreceiptitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='purchaseorderreceiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                    to='order.purchaseorderreceipt'),
        ),
        migrations.AddField(
            model_name='purchaseorderreceiptitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='ordertemplateitem',
            unique_together={('template', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='ordersplititem',
            unique_together={('order_split', 'order_item')},
        ),
    ]
