# Generated by Django 5.1.7 on 2025-03-16 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_currency'),
        ('order', '0002_purchaseorderitem_tax_purchaseorderitem_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='currency',
            field=models.ForeignKey(help_text='Die Währung, in der der Artikel bestellt wird', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Währung'),
        ),
    ]
